### PR TITLE
first pass at a pkgdown website

### LINKED ISSUE #7: Format documentation via pkgdown
We could use [pkgdown](https://pkgdown.r-lib.org/) to create a website that presents documentation in a way that will be especially appealing to folks who aren't computationally savvy. It would be a nice way to share tutorials/articles/vignettes that we develop for different use cases/datasets/audiences.

### LINKED ISSUE #21: ignore html and rendered md files?
I don't know if this is desirable to everyone else or not, but it would make development of the docs a bit easier! Happy to do this if it helps.

### PR DESCRIPTION
**Pull request by k8hertweck**
Resolves #7 (at least the very basic framework)

This PR gives you a package for which a website can be built using `pkg_down::build_site()`

- removed extraneous html and md files (resolves #21 , though they're not precisely ignored in place, the pkgdown automation places them in locations where they won't be tracked)
- moved quickstart Rmd to vignettes (to allow them to be easily rendered under the Articles section of the website)
- removed duplicate vignette files (older versions/copies/drafts); I kept a few that seemed to have novel content that may be useful

I think it looks pretty good and we can move forward with organizing and designing documentation using this framework. If you agree, you'll need to follow these instructions for ensuring we can publish it through gh-pages: "If you are using GitHub, the easiest way to make this your package website is to check into git, then go to settings for your repo and make sure that the GitHub pages source is set to “master branch /docs folder”. Be sure to update the URL on your github repository homepage so others can easily navigate to your new site." The site URL would be [ergony.github.io/omicser](https://ergony.github.io/omicser); it renders automatically from the name of the repo and GitHub account.

Other things I'm happy to work on:
- fix labeling of drop-down items in "Articles" section of website (basically, titles of the vignettes)
- organization of information between main page, getting started, etc
- other misc project organization things in the repo

Other things I can't do given my access: 
- setting up github actions
- contacting people who are testing with information about how they can access the webpage

### CODE REVIEW

**Comment by k8hertweck** [comment]
Here's a screen shot of the front page of the site:

Screen Shot 2021-09-24 at 12 45 43 PM

**Comment by k8hertweck** [comment]
And here's the drop down menu with vignettes. We can label the quickstart guides with numbers so it's clearer

Screen Shot 2021-09-24 at 12 47 17 PM

**Comment by ergonyc** [comment]
Looks good!

**Comment by ergonyc** [comment]
Probably I should have merged so immediately.  I will:

- [ ]  set up the github actions to render the site

**Comment by k8hertweck** [comment]
Awesome, thanks! I'll go ahead and start working on cleaning up the labels and whatnot.

**Pull request merged**
